# 01- Numpy

## Memory-efficient container that provides fast numerical operations

In [9]:
import numpy as np
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


## Python Lists VS Numpy Arrays

In [2]:
#python lists
L = range(1000)
%timeit [i**2 for i in L]

358 µs ± 23.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.71 µs ± 66.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


## Creating arrays [1-D Array, 2-D Array, 3-D Array]

In [5]:
#1-D Array
a = np.array([0, 1, 2, 3])
print("Dimension: {}".format(a.ndim))
print("Shape : {}".format(a.shape))
print("Length: {}".format(len(a)))

Dimension: 1
Shape : (4,)
Length: 4


In [7]:
#2-D Array
b = np.array([[0, 1, 2], [3, 4, 5]])
print("Dimension: {}".format(b.ndim))
print("Shape : {}".format(b.shape))
print("Length: {}".format(len(b)))

Dimension: 2
Shape : (2, 3)
Length: 2


In [8]:
#3-D Array
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print("Dimension: {}".format(c.ndim))
print("Shape : {}".format(c.shape))
print("Length: {}".format(len(c)))

Dimension: 3
Shape : (2, 2, 2)
Length: 2


## Array Functions

In [17]:
'''
arange is an array-valued version of the built-in Python range function
'''
a = np.arange(10) # 0.... n-1
b = np.arange(1, 10, 2) #start, end (exclusive), step
c = np.linspace(0, 1, 6) #start, end, number of points


print(a)
print('********************')
print(b)
print('********************')
print(c)
print('********************')


[0 1 2 3 4 5 6 7 8 9]
********************
[1 3 5 7 9]
********************
[0.  0.2 0.4 0.6 0.8 1. ]
********************


In [18]:
d = np.ones((3, 3)) #Create a matrix of 3-by-3 of entries 1
e = np.zeros((3, 3)) #Create a matrix of 3-by-3 of entries 1
f = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

print(d)
print('********************')
print(e)
print('********************')
print(f)
print('********************')


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
********************
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
********************
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
********************


In [21]:
g = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0
h = np.diag([1, 2, 3, 4]) #construct a diagonal array.
i = np.diag(a)   #Extract diagonal

print(g)
print('********************')
print(h)
print('********************')
print(i)
print('********************')



[[1. 0.]
 [0. 1.]
 [0. 0.]]
********************
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
********************
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]
********************


In [20]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
j = np.random.rand(4) 
k = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***
print(j)
print('********************')
print(k)
print('********************')

[0.70991128 0.69855419 0.1788118  0.26189167]
********************
[-0.19041319  0.03840441 -0.0633439   0.82998788]
********************


## Basic DataTypes

In [22]:
a = np.arange(10)
b = np.arange(10, dtype='float64') #explicitly specify the data-type
c = np.zeros((3, 3)) #The default data type is float for zeros and ones function
d = np.array([1+2j, 2+4j])   #Complex datatype
e = np.array([True, False, True, False])  #Boolean datatype
f = np.array(['Ram', 'Robert', 'Rahim'])
print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)
print(e.dtype)
print(f.dtype)


int32
float64
float64
complex128
bool
<U6


# Indexing and Slicing

In [24]:
a = np.arange(10)
print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [30]:
# For multidimensional arrays, indexes are tuples of integers:
a = np.diag([1, 2, 3])
print(a[1, 1])

2


In [26]:
a[2, 1] = 5 #assigning value
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [32]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [34]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [35]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])